# This workflow will build a Python app and deploy it to an Azure Functions App on Linux when a commit is pushed to your default branch.
#
# This workflow assumes you have already created the target Azure Functions app.
# For instructions see https://learn.microsoft.com/en-us/azure/azure-functions/create-first-function-vs-code-python?pivots=python-mode-configuration
#
# To configure this workflow:
# 1. Set up the following secrets in your repository:
#   - AZURE_FUNCTIONAPP_PUBLISH_PROFILE
# 2. Change env variables for your configuration.
#
# For more information on:
#   - GitHub Actions for Azure: https://github.com/Azure/Actions
#   - Azure Functions Action: https://github.com/Azure/functions-action
#   - Publish Profile: https://github.com/Azure/functions-action#using-publish-profile-as-deployment-credential-recommended
#   - Azure Service Principal for RBAC: https://github.com/Azure/functions-action#using-azure-service-principal-for-rbac-as-deployment-credential
#
# For more samples to get started with GitHub Action workflows to deploy to Azure: https://github.com/Azure/actions-workflow-samples/tree/master/FunctionApp

name: üöÄ Deploy Python project to Azure Function App

on:
  push:
    branches: ["python-fastapi-azure-cicd-github-actions"]

env:
  AZURE_FUNCTIONAPP_NAME: 'fun-based-on-app-service'    # set this to your function app name on Azure
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'                   # set this to the path to your function app project, defaults to the repository root
  PYTHON_VERSION: '3.12.x'                              # set this to the python version to use (e.g. '3.6', '3.7', '3.8')

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for OIDC
      contents: read  # Required for actions/checkout
    steps:
    - name: üïê Checkout GitHub Action
      uses: actions/checkout@v4
    
    - name: üïë Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: üïí Resolve Project Dependencies Using Pip
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/site-packages"        

    - name: üïì Log in to Azure with AZ CLI
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}             # Required to log in with OIDC
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}             # Required to log in with OIDC
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} # Required to log in with OIDC

    - name: üïî Run the Azure Functions Action
      uses: Azure/functions-action@v1
      id: deploy-to-function-app
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}